version: 2
jobs:
  build:
    branches:
      only: master
    docker:
      -image: circleci/node:7.10
    steps:
      - checkout
      - restore_cache:
        Key: dependency-cache-{{ checksum "package.json"}}
        Key: v1-dependencies-

      - run:
          name: Install dependencies
          command: npm install 
        
      - save_cache:
        paths:
          - node_modules
        Key: v1-dependencies-{{ checksum "package.json"}}

      - run:
          name: test
          command: echo "no test"

      - run:
          name: build 
          command: npm run build
      
      - run:
          name: Install awscli
          command: |
            sudo apt-get install python-pip python-dev
            sudo pip install awscli
      
      - run: 
          name: Deploy to S3 Production
          command: aws s3 sync public s3://path-to-s3 --delete --cache-control "max-age=3153600"

      - run:
          name: Enable cloudfront feature
          command: aws configure set preview.create-invalidation true
      
      - run:
          name: Start cloudfront invaldiation
          command: aws cloudfront create-invalidation --cli-input-json {\"DistributionId\":\"$CLOUD_FRONT_INSTANCE\",\"InvalidationBatch\":{\"Paths\":{\Quantity\":1,\"Items\":[\"/*\"]},\"CallerReference\":"$(date +%s)\"}}
